# 공통 설정
spring:
  application:
    name: caro
  profiles:
    active: local  # 기본 profile을 local
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  jpa:
    open-in-view: false  # OSIV off
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
  modulith:
    runtime:
      flyway-enabled: true

server:
  shutdown: graceful

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, prometheus
  endpoint:
    health:
      show-details: always
