spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/seed-dev
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD}

logging:
  level:
    root: INFO
    com.whatever.caro: DEBUG
    org.flywaydb: DEBUG
    org.springframework.modulith: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
