spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        generate_statistics: false
  flyway:
    clean-disabled: true
    locations: classpath:db/migration,classpath:db/seed-prod
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT:6379}
      username: ${REDIS_USERNAME:}
      password: ${REDIS_PASSWORD}

management:
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: INFO
    com.whatever.caro: INFO
