spring:
  application:
    name: ${OTEL_SERVICE_NAME:caro-backend}
  profiles:
    active: local  # 기본 profile을 local
  threads:
    virtual:
      enabled: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
  datasource:
    hikari:
      connection-test-query: "SELECT 1"
  jpa:
    open-in-view: false  # OSIV off
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: true
        globally_quoted_identifiers: true
        order_updates: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: UTC
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    out-of-order: false
    clean-disabled: true
    connect-retries: 3
    connect-retries-interval: 2s
  modulith:
    runtime:
      flyway-enabled: true

server:
  port: 8080
  shutdown: graceful

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health, info, metrics, modulith
  endpoint:
    health:
      show-details: always
  otlp:
    metrics:
      export:
        url: ${OTLP_ENDPOINT:http://localhost:4318}/v1/metrics
        step: 15s
        headers:
          tenant_id: ${TENANT_ID:caro-backend-staging}
        histogram-flavor: base2-exponential-bucket-histogram
        max-scale: 20
        max-bucket-count: 160
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  opentelemetry:
    logging:
      export:
        otlp:
          endpoint: ${OTLP_ENDPOINT:http://localhost:4318}/v1/logs
          transport: http
          headers:
            tenant_id: ${TENANT_ID:caro-backend-staging}
    tracing:
      export:
        otlp:
          transport: http
          endpoint: ${OTLP_ENDPOINT:http://localhost:4318}/v1/traces
          headers:
            tenant_id: ${TENANT_ID:caro-backend-staging}
  tracing:
    sampling:
      probability: 1.0
    baggage:
      enabled: true
      correlation:
        fields:
          - "trace_id"
          - "span_id"
          - "module.source"
          - "module.target"
