name: ✨Feature
description: 새로운 기능 개발
title: "[Feature] "
type: "✨Feature"
labels: ["type: feature"]
projects: ["whatever-x/26"]
body:
  - type: textarea
    id: description
    attributes:
      label: 구현 내용
      placeholder: |
        예: 결제 취소 API 구현
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: 완료 조건
      placeholder: |
        - [ ] API 구현
        - [ ] 테스트 작성
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: 우선순위
      options:
        - P0
        - P1
        - P2
        - P3
      default: 2
