-- Spring Modulith 2.0.x requires BINARY(16) for id and camelCase column names
ALTER TABLE EVENT_PUBLICATION
    MODIFY COLUMN ID BINARY(16) NOT NULL,
    RENAME COLUMN LISTENER_ID TO listenerId,
    RENAME COLUMN EVENT_TYPE TO eventType,
    RENAME COLUMN SERIALIZED_EVENT TO serializedEvent,
    RENAME COLUMN PUBLICATION_DATE TO publicationDate,
    RENAME COLUMN COMPLETION_DATE TO completionDate,
    RENAME COLUMN COMPLETION_ATTEMPTS TO completionAttempts,
    RENAME COLUMN LAST_RESUBMISSION_DATE TO lastResubmissionDate;

ALTER TABLE EVENT_PUBLICATION_ARCHIVE
    MODIFY COLUMN ID BINARY(16) NOT NULL,
    RENAME COLUMN LISTENER_ID TO listenerId,
    RENAME COLUMN EVENT_TYPE TO eventType,
    RENAME COLUMN SERIALIZED_EVENT TO serializedEvent,
    RENAME COLUMN PUBLICATION_DATE TO publicationDate,
    RENAME COLUMN COMPLETION_DATE TO completionDate,
    RENAME COLUMN COMPLETION_ATTEMPTS TO completionAttempts,
    RENAME COLUMN LAST_RESUBMISSION_DATE TO lastResubmissionDate;
